# Generated by Django 4.0.6 on 2022-07-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=25)),
                ('tanggal_lahir', models.DateField()),
                ('alamat', models.TextField()),
                ('foto', models.FileField(upload_to='')),
            ],
        ),
    ]
