# Generated by Django 4.0.6 on 2022-07-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teman',
            name='tanggal_lahir',
        ),
        migrations.AddField(
            model_name='teman',
            name='umur',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
